# Generated by Django 6.0.3 on 2026-04-08 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_producto_options_producto_actualizado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='products.categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
    ]
