# Generated by Django 6.0.4 on 2026-05-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_producto_imagen'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['slug'], name='products_ca_slug_8db331_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug'], name='products_pr_slug_01981e_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='products_pr_activo_5016eb_idx'),
        ),
    ]
