# Generated by Django 5.2.14 on 2026-08-01 16:03

from django.db import migrations, models


def poblar_total_vendido(apps, schema_editor):
    """Backfill total_vendido a partir de líneas de pedidos reales (no borradores)."""
    Producto = apps.get_model('products', 'Producto')
    LineaPedido = apps.get_model('checkout', 'LineaPedido')
    Pedido = apps.get_model('checkout', 'Pedido')

    pedidos_reales = Pedido.objects.exclude(estado='borrador').values_list('id', flat=True)
    if not pedidos_reales:
        return

    from django.db.models import Sum
    ventas = (
        LineaPedido.objects
        .filter(pedido_id__in=pedidos_reales)
        .values('producto_id')
        .annotate(total=Sum('cantidad'))
    )

    for venta in ventas:
        Producto.objects.filter(pk=venta['producto_id']).update(total_vendido=venta['total'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_producto_en_oferta_producto_precio_oferta_and_more'),
        ('checkout', '0006_simplificar_choices_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='total_vendido',
            field=models.PositiveIntegerField(default=0, verbose_name='Total vendido'),
        ),
        migrations.RunPython(poblar_total_vendido, migrations.RunPython.noop),
    ]
