# Generated by Django 5.2.14 on 2026-08-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_categoria_imagen_producto_destacado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='orden_destacado',
            field=models.PositiveIntegerField(default=0, help_text='Controla el orden exacto de los productos destacados en el Home (menor = primero). Se usa cuando "Destacado" está activo.', verbose_name='Orden destacado'),
        ),
    ]
