# Generated by Django 5.2.14 on 2026-05-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_direccionenvio_usuario_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionenvio',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='direccionenvio',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número/Apto'),
        ),
    ]
