# Generated by Django 5.2.14 on 2026-05-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_direccionenvio_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccionenvio',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Dirección de Envío', 'verbose_name_plural': 'Direcciones de Envío'},
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='email',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='es_direccion_predeterminada',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='tipo_domicilio',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='descripcion_error',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='fecha_completado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='referencia_pago',
        ),
        migrations.AlterField(
            model_name='direccionenvio',
            name='pais',
            field=models.CharField(default='Cuba', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
