# Generated by Django 5.2.14 on 2026-07-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('imagen', models.ImageField(upload_to='banner/', verbose_name='Imagen')),
                ('link', models.CharField(blank=True, help_text='URL a la que apunta el botón', max_length=500, verbose_name='Enlace')),
                ('texto_boton', models.CharField(default='Ver más', max_length=100, verbose_name='Texto del botón')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['orden'],
            },
        ),
    ]
