# Generated by Django 5.2.15 on 2026-07-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='imagen_movil',
            field=models.ImageField(blank=True, help_text='Versión del banner para dispositivos móviles. Si se deja vacía, se usará la imagen de escritorio.', null=True, upload_to='banner/', verbose_name='Imagen (Móvil)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagen',
            field=models.ImageField(upload_to='banner/', verbose_name='Imagen (Escritorio)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='texto_boton',
            field=models.CharField(blank=True, default='Ver más', max_length=100, verbose_name='Texto del botón'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
    ]
