# Generated by Django 5.2.14 on 2026-08-01 17:18

import django.db.models.deletion
from django.db import migrations, models


def sembrar_secciones(apps, schema_editor):
    """Crea las secciones del Home con su orden y contenido por defecto."""
    HomeSeccion = apps.get_model('home', 'HomeSeccion')
    Beneficio = apps.get_model('home', 'Beneficio')

    secciones_data = [
        ('categorias', 'Categorías Destacadas', 10),
        ('destacados', 'Productos Destacados', 20),
        ('mas_vendidos', 'Más Vendidos', 30),
        ('ofertas', 'Ofertas Especiales', 40),
        ('nuevos', 'Nuevos Productos', 50),
        ('beneficios', '¿Por qué comprar con nosotros?', 60),
    ]

    secciones = {}
    for tipo, titulo, orden in secciones_data:
        secciones[tipo] = HomeSeccion.objects.create(
            tipo=tipo, titulo=titulo, orden=orden, limite=8, activo=True
        )

    beneficios_data = [
        ('seguro', 'Pago seguro', 'Tus pagos están protegidos con los estándares de seguridad más altos.'),
        ('envio', 'Envío rápido', 'Entregas ágiles para que recibas tus productos en tiempo récord.'),
        ('garantia', 'Garantía de calidad', 'Productos seleccionados con garantía de calidad y satisfacción.'),
        ('atencion', 'Atención al cliente', 'Soporte personalizado antes, durante y después de tu compra.'),
        ('verificado', 'Productos verificados', 'Cada artículo es revisado y verificado antes de enviarse.'),
        ('compra', 'Compra sencilla', 'Proceso de compra rápido e intuitivo en solo unos pasos.'),
    ]
    seccion_beneficios = secciones['beneficios']
    for orden, (icono, titulo, texto) in enumerate(beneficios_data):
        Beneficio.objects.create(
            seccion=seccion_beneficios,
            icono=icono,
            titulo=titulo,
            texto=texto,
            orden=orden,
            activo=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_imagen_movil_alter_banner_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('categorias', 'Categorías destacadas'), ('destacados', 'Productos destacados'), ('mas_vendidos', 'Productos más vendidos'), ('ofertas', 'Ofertas especiales'), ('nuevos', 'Productos nuevos'), ('beneficios', 'Beneficios de la tienda')], max_length=20, unique=True, verbose_name='Tipo de sección')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor número = aparece antes', verbose_name='Orden')),
                ('limite', models.PositiveIntegerField(default=8, help_text='Cantidad máxima de productos o categorías a mostrar', verbose_name='Límite')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Sección del Home',
                'verbose_name_plural': 'Secciones del Home',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(choices=[('seguro', 'Pago seguro'), ('envio', 'Envío rápido'), ('garantia', 'Garantía de calidad'), ('atencion', 'Atención al cliente'), ('verificado', 'Productos verificados'), ('compra', 'Compra sencilla'), ('reembolso', 'Reembolso garantizado'), ('soporte', 'Soporte 24/7')], default='seguro', max_length=30, verbose_name='Icono')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('texto', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='home.homeseccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
                'ordering': ['orden'],
            },
        ),
        migrations.RunPython(sembrar_secciones, migrations.RunPython.noop),
    ]
