# Generated by Django 5.2.14 on 2026-08-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homeseccion_beneficio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerIntermedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('imagen', models.ImageField(upload_to='banner-intermedio/', verbose_name='Imagen (Escritorio)')),
                ('imagen_movil', models.ImageField(blank=True, null=True, upload_to='banner-intermedio/', verbose_name='Imagen (Móvil)')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Enlace')),
                ('texto_boton', models.CharField(blank=True, default='Ver más', max_length=100, verbose_name='Texto del botón')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Banner Intermedio',
                'verbose_name_plural': 'Banners Intermedios',
                'ordering': ['orden'],
            },
        ),
    ]
