# Generated by Django 5.2.14 on 2026-08-29 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bannerintermedio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeColeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='home-colecciones/', verbose_name='Imagen')),
                ('enlace', models.CharField(blank=True, help_text='URL al que apunta el bloque', max_length=500, verbose_name='Enlace')),
                ('texto_boton', models.CharField(blank=True, default='Descubrir', max_length=100, verbose_name='Texto del botón')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Bloque de inspiración',
                'verbose_name_plural': 'Bloques de inspiración',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HomeEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('imagen', models.ImageField(upload_to='home-editorial/', verbose_name='Imagen (Escritorio)')),
                ('imagen_movil', models.ImageField(blank=True, help_text='Versión para móviles. Si se deja vacía se usará la de escritorio.', null=True, upload_to='home-editorial/', verbose_name='Imagen (Móvil)')),
                ('texto_boton', models.CharField(blank=True, default='Descubrir', max_length=100, verbose_name='Texto del botón')),
                ('enlace', models.CharField(blank=True, help_text='URL a la que apunta el botón', max_length=500, verbose_name='Enlace')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Bloque editorial',
                'verbose_name_plural': 'Bloques editoriales',
                'ordering': ['orden'],
            },
        ),
        migrations.DeleteModel(
            name='BannerIntermedio',
        ),
        migrations.AddField(
            model_name='homeseccion',
            name='layout',
            field=models.CharField(blank=True, choices=[('carousel', 'Carrusel horizontal'), ('grid', 'Cuadrícula'), ('ranking', 'Ranking numerado'), ('editorial', 'Editorial / asimétrico'), ('promo', 'Bloque promocional'), ('categories', 'Categorías circulares'), ('benefits', 'Beneficios (iconos)')], help_text='Cómo se presenta visualmente la sección. Si se deja vacío se usa el layout por defecto del tipo.', max_length=20, verbose_name='Layout (presentación)'),
        ),
        migrations.AddField(
            model_name='homeseccion',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Texto secundario que acompaña al título (opcional).', max_length=300, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='homeseccion',
            name='tipo',
            field=models.CharField(choices=[('categorias', 'Categorías destacadas'), ('destacados', 'Productos destacados'), ('mas_vendidos', 'Productos más vendidos'), ('ofertas', 'Ofertas especiales'), ('nuevos', 'Productos nuevos'), ('editorial', 'Bloque editorial'), ('colecciones', 'Descubre / Inspiración'), ('beneficios', 'Beneficios de la tienda')], max_length=20, unique=True, verbose_name='Tipo de sección'),
        ),
        migrations.AddField(
            model_name='homecoleccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecciones', to='home.homeseccion', verbose_name='Sección'),
        ),
        migrations.AddField(
            model_name='homeeditorial',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editoriales', to='home.homeseccion', verbose_name='Sección'),
        ),
    ]
